name: github-pipelines

on:
  push:
    branches:
      - main
      - production
      - feature/**
      - bugfix/**

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build Go app
        run: go build -o myapp

      - name: Build and push Docker image
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker build -t ruslanmakovchik/lastone:latest .
          docker push ruslanmakovchik/lastone:latest

      - name: Deploy container
        run: |
          docker stop lastone 2>$null
          docker rm lastone 2>$null
    
          docker run -d --name lastone -p 8888:8888 ruslanmakovchik/lastone:latest