image: golang:1.24.0

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          runs-on:
            - windows
          script:
            - echo "Running on a local runner"
            - go version
            - go mod tidy
            - go test ./...
            - echo "Build Completed!"

      - step:
          name: Build and Push Docker Image
          services:
            - docker
          script:
            - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            - docker build -t RuslanM36/lastone:latest .
            - docker push RuslanM36/lastone:latest
      
      - step:
          name: Run
          runs-on:
            - windows
            - self.hosted
          script:
            - docker run -d -p 88:8888 RuslanM36/lastone:latest