name: Go CI/CD Pipeline

on:
  push:
    branches:
      - master   
  pull_request:
    branches:
      - master   

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2  

      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.0  

      
      - name: Install dependencies
        run: go mod tidy  

      
      - name: Run tests
        run: go test ./...  

      
      - name: Build application
        run: go build -v  

  
  docker-build-and-deploy:
    needs: build-and-test  
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/flooring-calculator:latest

      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flooring-calculator:latest

      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/flooring-calculator:latest
            docker stop flooring-calculator || true
            docker rm flooring-calculator || true
            docker run -d -p 8080:8080 --name flooring-calculator ${{ secrets.DOCKER_USERNAME }}/flooring-calculator:latest
