name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - production
      - feature/*
      - bugfix/*

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build Go app
        run: go build -o myapp

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t RuslanM36/lastone:latest .
          docker push RuslanM36/lastone:latest

      - name: Deploy container
        run: |
          docker stop my-app-go || true
          docker rm my-app-go || true
          docker run -d --name my-app-go -p 8888:8888 RuslanM36/lastone:latest