name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main  
      - staging  
env:
  DOCKER_IMAGE: RuslanM36/lastone
  DOCKER_TAG: latest

jobs:
  test:
    name: Build and Test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Install dependencies
      run: go mod tidy
      
    - name: Run tests
      run: go test ./...
  
  build-docker:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
    
  deploy:
    name: Deploy
    needs: build-docker
    runs-on: self-hosted
    steps:
    - name: Run container
      run: |
        docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        docker run -d -p 88:8888 ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}