name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - production
      - feature/*
      - bugfix/*

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build Go app
        run: go build -o myapp

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ruslanm36/my-go-app:latest .
          docker push ruslanm36/my-go-app:latest

      - name: Deploy container
        run: |
          docker stop my-go-app || true
          docker rm my-go-app || true
          docker run -d --name my-go-app -p 8080:8080 ruslanm36/my-go-app:latest