name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - production
      - feature/*
      - bugfix/*

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build and push Docker image
        run: |
          $pass = "${{ secrets.DOCKERHUB_PASSWORD }}"
          $pass | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build -t docker.io/ruslanm36/lastone:latest .
          docker push docker.io/ruslanm36/lastone:latest

      - name: Deploy container
        run: |
          docker stop lastone || true
          docker rm lastone || true
          docker run -d --name lastone -p 8888:8888 docker.io/ruslanm36/lastone:latest